# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\программы\Яндекс.Лицей\2 год\17\design3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1252, 889)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(19)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(460, 10, 501, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setEnabled(True)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/Acer/.designer/backup/fire.png"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 180, 410, 376))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.choice_dir_button_from_copy = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.choice_dir_button_from_copy.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 170, 0);\n"
"background-color: rgb(85, 85, 127);")
        self.choice_dir_button_from_copy.setObjectName("choice_dir_button_from_copy")
        self.horizontalLayout_5.addWidget(self.choice_dir_button_from_copy)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_32.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_6.addWidget(self.label_32)
        self.choice_dir_button_to_copy = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.choice_dir_button_to_copy.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 170, 0);\n"
"background-color: rgb(85, 85, 127);")
        self.choice_dir_button_to_copy.setObjectName("choice_dir_button_to_copy")
        self.horizontalLayout_6.addWidget(self.choice_dir_button_to_copy)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_31.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_4.addWidget(self.label_31)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.size_x_1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.size_x_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.size_x_1.setMinimum(1)
        self.size_x_1.setMaximum(1000000)
        self.size_x_1.setObjectName("size_x_1")
        self.horizontalLayout_12.addWidget(self.size_x_1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.size_y_1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.size_y_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.size_y_1.setMinimum(1)
        self.size_y_1.setMaximum(100000)
        self.size_y_1.setObjectName("size_y_1")
        self.horizontalLayout_12.addWidget(self.size_y_1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.cutting__in_good = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cutting__in_good.setStyleSheet("color: rgb(255, 170, 0);")
        self.cutting__in_good.setObjectName("cutting__in_good")
        self.verticalLayout_6.addWidget(self.cutting__in_good)
        self.save_proportions_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.save_proportions_2.setStyleSheet("color: rgb(255, 170, 0);")
        self.save_proportions_2.setObjectName("save_proportions_2")
        self.verticalLayout_6.addWidget(self.save_proportions_2)
        self.get_ramka_for_save = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.get_ramka_for_save.setStyleSheet("color: rgb(255, 170, 0);")
        self.get_ramka_for_save.setObjectName("get_ramka_for_save")
        self.verticalLayout_6.addWidget(self.get_ramka_for_save)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_25.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_14.addWidget(self.label_25)
        self.save_parametr_kachestvo = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.save_parametr_kachestvo.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.save_parametr_kachestvo.setMinimum(1)
        self.save_parametr_kachestvo.setMaximum(100)
        self.save_parametr_kachestvo.setProperty("value", 85)
        self.save_parametr_kachestvo.setObjectName("save_parametr_kachestvo")
        self.horizontalLayout_14.addWidget(self.save_parametr_kachestvo)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_7.addWidget(self.label_24)
        self.format_file_for_lot_cutting = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.format_file_for_lot_cutting.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.format_file_for_lot_cutting.setObjectName("format_file_for_lot_cutting")
        self.horizontalLayout_7.addWidget(self.format_file_for_lot_cutting)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.filename_a_lot_copy = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.filename_a_lot_copy.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.filename_a_lot_copy.setObjectName("filename_a_lot_copy")
        self.horizontalLayout_13.addWidget(self.filename_a_lot_copy)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.statr_copt_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.statr_copt_button.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 170, 0);\n"
"background-color: rgb(85, 85, 127);")
        self.statr_copt_button.setObjectName("statr_copt_button")
        self.horizontalLayout_9.addWidget(self.statr_copt_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 334, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.size_x_3 = QtWidgets.QLabel(self.layoutWidget)
        self.size_x_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.size_x_3.setObjectName("size_x_3")
        self.horizontalLayout.addWidget(self.size_x_3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.size_y_3 = QtWidgets.QLabel(self.layoutWidget)
        self.size_y_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.size_y_3.setObjectName("size_y_3")
        self.horizontalLayout.addWidget(self.size_y_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.label_30)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.size_x_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.size_x_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.size_x_2.setMinimum(1)
        self.size_x_2.setMaximum(100000)
        self.size_x_2.setObjectName("size_x_2")
        self.horizontalLayout_11.addWidget(self.size_x_2)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.size_y_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.size_y_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.size_y_2.setMinimum(1)
        self.size_y_2.setMaximum(1000000)
        self.size_y_2.setObjectName("size_y_2")
        self.horizontalLayout_11.addWidget(self.size_y_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.save_proportions_1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.save_proportions_1.setEnabled(True)
        self.save_proportions_1.setTabletTracking(False)
        self.save_proportions_1.setStyleSheet("color: rgb(255, 170, 0);")
        self.save_proportions_1.setChecked(False)
        self.save_proportions_1.setObjectName("save_proportions_1")
        self.verticalLayout_5.addWidget(self.save_proportions_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(56)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.format_file_wath_program = QtWidgets.QLineEdit(self.layoutWidget)
        self.format_file_wath_program.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.format_file_wath_program.setObjectName("format_file_wath_program")
        self.horizontalLayout_3.addWidget(self.format_file_wath_program)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(980, 10, 258, 341))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.choice_dir_button_wath = QtWidgets.QPushButton(self.layoutWidget1)
        self.choice_dir_button_wath.setAutoFillBackground(False)
        self.choice_dir_button_wath.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 85, 127);\n"
"")
        self.choice_dir_button_wath.setObjectName("choice_dir_button_wath")
        self.horizontalLayout_10.addWidget(self.choice_dir_button_wath)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.choice_file_lable = QtWidgets.QLabel(self.layoutWidget1)
        self.choice_file_lable.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.choice_file_lable.setObjectName("choice_file_lable")
        self.verticalLayout_4.addWidget(self.choice_file_lable)
        self.list_file_in_dir = QtWidgets.QListWidget(self.layoutWidget1)
        self.list_file_in_dir.setStyleSheet("color: rgb(255, 170, 0);")
        self.list_file_in_dir.setAlternatingRowColors(True)
        self.list_file_in_dir.setIconSize(QtCore.QSize(400, 400))
        self.list_file_in_dir.setModelColumn(0)
        self.list_file_in_dir.setObjectName("list_file_in_dir")
        self.verticalLayout_4.addWidget(self.list_file_in_dir)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.pokas = QtWidgets.QPushButton(self.layoutWidget1)
        self.pokas.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 170, 0);")
        self.pokas.setObjectName("pokas")
        self.horizontalLayout_8.addWidget(self.pokas)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.out_print_list_copy_file = QtWidgets.QListWidget(self.centralwidget)
        self.out_print_list_copy_file.setGeometry(QtCore.QRect(980, 360, 256, 291))
        self.out_print_list_copy_file.setStyleSheet("color: rgb(0, 170, 0);")
        self.out_print_list_copy_file.setAlternatingRowColors(True)
        self.out_print_list_copy_file.setIconSize(QtCore.QSize(400, 400))
        self.out_print_list_copy_file.setModelColumn(0)
        self.out_print_list_copy_file.setObjectName("out_print_list_copy_file")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1252, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.list_file_in_dir.currentTextChanged['QString'].connect(self.choice_file_lable.setText)
        self.list_file_in_dir.currentTextChanged['QString'].connect(self.choice_file_lable.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_19.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">100</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "Cкопировать все файлы:"))
        self.label_22.setWhatsThis(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#55ffff;\">100апочпо</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Из"))
        self.choice_dir_button_from_copy.setText(_translate("MainWindow", "(Выбрать папку)"))
        self.label_32.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">100</span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "В"))
        self.choice_dir_button_to_copy.setText(_translate("MainWindow", "(Выбрать папку)"))
        self.label_31.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">100</span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "Максимальный\n"
"размер"))
        self.label_13.setText(_translate("MainWindow", "X"))
        self.cutting__in_good.setText(_translate("MainWindow", "Обрезать по меньшей стороне"))
        self.save_proportions_2.setText(_translate("MainWindow", "Сохранять пропорции"))
        self.get_ramka_for_save.setText(_translate("MainWindow", "Добавить рамку для сохранения пропорций"))
        self.label_25.setWhatsThis(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#55ffff;\">100апочпо</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "Качество"))
        self.label_24.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">100</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "Формат"))
        self.format_file_for_lot_cutting.setText(_translate("MainWindow", ".jpg"))
        self.label_23.setWhatsThis(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#55ffff;\">100апочпо</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Имя конечного\n"
"файла"))
        self.filename_a_lot_copy.setText(_translate("MainWindow", "cat"))
        self.statr_copt_button.setText(_translate("MainWindow", "Запустить копирование"))
        self.label_6.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">100</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Size"))
        self.size_x_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">100</span></p></body></html>"))
        self.size_x_3.setText(_translate("MainWindow", "500"))
        self.label_5.setText(_translate("MainWindow", "X"))
        self.size_y_3.setText(_translate("MainWindow", "500"))
        self.label_30.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">100</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "Изменить\n"
"размер"))
        self.label_12.setText(_translate("MainWindow", "X"))
        self.save_proportions_1.setText(_translate("MainWindow", "Сохранять пропорции"))
        self.label_17.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">100</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "Изменить\n"
"формат"))
        self.format_file_wath_program.setText(_translate("MainWindow", ".jpg"))
        self.choice_dir_button_wath.setText(_translate("MainWindow", "Выберите папку\n"
"для просмотра"))
        self.choice_file_lable.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">100</span></p></body></html>"))
        self.choice_file_lable.setText(_translate("MainWindow", "Выбранный файл"))
        self.pokas.setText(_translate("MainWindow", "     Показать    "))

